bitcoin/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostFeed


app_name = 'bitcoin'


urlpatterns = [
# post views
            path('', views.post_list, name='post_list'),
            path('<int:year>/<int:month>/<int:day>/<slug:post>/',
                    views.post_detail,
                    name='post_detail'),
                    path('<int:post_id>/share/',
                                                views.post_share, name='post_share'),
            path('feed/',LatestPostFeed(), name='post_feed'),
            path('search/', views.post_search, name='post_search'),
        
]

bitlipa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from bitcoin.sitemaps import Postsitemap

sitemaps = {
    'post':Postsitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bitcoin/', include('bitcoin.urls', namespace='bitcoin')),
    path('sitemap.xml',sitemap,{'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

bitcoin/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                    self).get_queryset()\
                                    .filter(status='published')
class Post(models.Model):
    STATUS_CHOICES = (
                        ('draft', 'Draft'),
                        ('published', 'Published'),
                    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                                    on_delete=models.CASCADE,
                                    related_name='bitcoin_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                                choices=STATUS_CHOICES,
                                default='published')
    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('bitcoin:post_detail',
                        args=[self.publish.year,
                                        self.publish.month,
                                        self.publish.day, self.slug])
    class Meta:
        ordering = ('-publish',)
    def __str__(self):
        return self.title


class comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name= models.CharField(max_length=80)
    email = models.EmailField()
    body= models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default = True)

    class meta:
        ordering =('created',)
    
    def __str__(self):
        return f'comment by {self.name} on {self.post }'
    

bitcoin/forms.py
from django import forms
from .models import comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments =forms.CharField(widget=forms.Textarea, required=False)

class commentForm(forms.ModelForm):
    class Meta:
        model = comment
        fields = ('name','email','body')
class SearchForm(forms.Form):
    query = forms.CharField()
    
    

bitcoin/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm, commentForm, SearchForm
from django.core.mail import send_mail
from django.contrib.postgres.search import SearchVector,SearchRank, SearchQuery

def post_list(request):
    object_list= Post.published.all()
    paginator =Paginator(object_list, 3) #3 post per each page
    page = request.GET.get('page')
    try:
        posts =paginator.page(page)
    except PageNotAnInteger:
        #if page is not an interger deliver the first page
        posts=paginator.page(1)
    except EmptyPage:
        #if the page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request,
                    'bitcoin/post/list.html',
                    {'page':page,
                        'posts': posts})     

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                    status='published',
                                    publish__year=year,
                                    publish__month=month,
                                    publish__day=day)
    #list of active comments for this post
    comments = post.comments.filter(active=True)
    new_comment =None
    comment_form = commentForm()
    if request.method=='POST':
        #comment was posted
        comment_form = commentForm(data=request.POST)
        if comment_form.is_valid():
            #create comment object but dont save it to the database yet
            new_comment=comment_form.save(commit=False)
            #assign the current post to the comment
            new_comment.post=post
            #save the commet to the database
            new_comment.save()
        else:
            comment_form=commentForm()
    return render(request,
                        'bitcoin/post/detail.html',
                        {'post': post,
                        'comments':comments,
                        'new_comment': new_comment,'comment_form':comment_form})  

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent =  False

    if request.method =="POST":
        #form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            #form passed validation
            cd =form.cleaned_data
            #...send email
            post_url = request.build_absolute_uri(
                                    post.get_absolute_url())
            subject = f"{cd['name']} recommends you read "f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'kevinisaackareithi@gmail.com',[cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'bitcoin/post/share.html',{'post':post,'form':form, 'sent':sent})

def post_search(request):
    form = SearchForm()
    query = None
    results =[]
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title','body')
            search_query = SearchQuery(query)
            results = Post.published.annotate(
                search = search_vector,
                rank = SearchRank(search_vector, search_query)
            ).filter(search=search_query).order_by('-rank')
    return render(request,
                    'bitcoin/post/search.html',
                    {'form':form,
                    'query':query,
                    'results':results
                    }
    )

bitcoin/templates/bitcoin/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}{% endblock %}</title>
<link href="{% static "css/bitcoin.css" %}" rel="stylesheet">
</head>
<body>
<div id="content">
{% block content %}
{% endblock %}
</div>
<div id="sidebar">
<h2>My blog</h2>
<p>This is my blog. I have written {% total_post%} post so far</p>
<h3> Latest post </h3>
{% show_latest 3 %}
<h3> Most comment post </h3>
{% get_most_commented_post as most_commented_post%}
<ul>
{% for post in most_commented_post%}
<li> 
<a href="{{ post.get_absolute_url}}">{{ post.title}} </a>
</li>
{% endfor%}
</ul>
<p>
    <a href="{% url "bitcoin:post_feed"%}">subscribe to my RSS</a>
</p>
<p> <a href="{% url "bitcoin:post_search"%}"> Search for something</a></p>
</div>
</body>
</html>

bitcoin/templates/bitcoin/pagination.html
<div class="pagination">
<span class="step-links">
{% if page.has_previous %}
<a href="?page={{ page.previous_page_number }}">Previous</a>
{% endif %}
<span class="current">
Page {{ page.number }} of {{ page.paginator.num_pages }}.
</span>
{% if page.has_next %}
<a href="?page={{ page.next_page_number }}">Next</a>
{% endif %}
</span>
</div>

bitcoin/templates/bitcoin/post/detail.html
{% extends "bitcoin/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
<h1>{{ post.title }}</h1>
<p class="date">
Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|markdown }}
<p>
<a href="{% url "bitcoin:post_share" post.id %}">
Share this post
</a>
</p>
{% with comments.count as total_comments %}
    <h2> 
    {{total_comments}} comment {{total_comments|pluralize}}
        </h2>
{% endwith%}
{% for comment in comments %}
<div class="comment">
<p class ="info">
    comment {{ forloop.counter}} by {{comment.name }} {{ comment.created}}
</p>
{{comment.body|linebreaks}}
</div>
{% empty%}
<p> There is no comment no this post yet</p>
{% endfor%}
{% if new_comment%}
<h2> your comment has been added succefully </h2>
{% else%}
<h2> add a new comment </h2>
<form method="Post">
{{comment_form.as_p}}
{% csrf_token %}
<p> <input type="submit" value="add comment"></p>
</form>
{% endif%}
{% endblock %}

bitcoin/templates/bitcoin/post/latest_post.html
<ul>
{% for post in latest_post %}
<li>
<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</li>
{% endfor %}
</ul>

bitcoin/templates/bitcoin/post/list.html
{% extends "bitcoin/base.html" %}
{% load blog_tags %}
{% block title %}My Blog{% endblock %}
{% block content %}
<h1>My Blog</h1>
{% for post in posts %}
<h2>
<a href="{{ post.get_absolute_url }}">
{{ post.title }}
</a>
</h2>
<p class="date">
Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|markdown|truncatewords_html:30 }}
{% endfor %}
{% include "bitcoin/pagination.html" with page=posts %}
<p class="tags"> Tags: {{ Post.tags.all|join:","}} </p>
{% endblock %}

bitcoin/templates/bitcoin/post/search.html
{% extends "bitcoin/base.html" %} 
{% load blog_tags %}
{% block title %}Search{% endblock %} 
{% block content %}
  {% if query %}
    <h1>Posts containing "{{ query }}"</h1>     
    <h3>
      {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}       
        {% endwith %}
    </h3>
    {% for post in results %}
      <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
      {{ post.body|markdown|truncatewords_html:5 }}     
      {% empty %}
      <p>There are no results for your query.</p>     
      {% endfor %}
    <p><a href="{% url "bitcoin:post_search" %}">Search again</a></p>   
    {% else %}
    <h1>Search for posts</h1>     
    <form method="get">       
        {{ form.as_p }}
      <input type="submit" value="Search">     
    </form>
  {% endif %}
{% endblock %}

bitcoin/templates/bitcoin/post/share.html
{% extends "bitcoin/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
{% if sent %}
<h1>E-mail successfully sent</h1>
<p>
"{{ post.title }}" was successfully sent to {{ form.cleaned_
data.to }}.
</p>
{% else %}
<h1>Share "{{ post.title }}" by e-mail</h1>
<form method="post">
{{ form.as_p }}
{% csrf_token %}
<input type="submit" value="Send e-mail">
</form>
{% endif %}
{% endblock %}